baseURL = "http://example.org/"
languageCode = 'pt-bt'
title = 'My New Hugo Site'
theme = 'docsy'

[[menu.main]]
	name = "Documentos"
	weight = 1
	url = "/docs/"

[[menu.main]]
	name = "Sobre"
	weight = 2
	url = "/docs/"

[[menu.main]]
	name = "GitHub"
	weight = 3
	url = "https://github.com/google/docsy/"
	pre = "<i class='fa-brands fa-github'></i>"
	post = "<span class='alert'>New teste!</span>"

[[menu.main]]
  name = "Produtos"
  identifier = "products"
  url = "/products/"
  weight = 2

  [[menu.main.products]]
    name = "Novos Produtos"
    identifier = "new-products"
    url = "/products/new/"
    weight = 1

  [[menu.main.products]]
    name = "Em Destaque"
    identifier = "featured-products"
    url = "/products/featured/"
    weight = 2